### ISSUE TITLE
Help with HLS Support?

### ISSUE THREAD

**Issue by willowell** [cjwcommuny/NovaHaskellTreeSitter#7]
Hello!

Thank you for putting this extension together.

Have you looked into adding support for HLS? Do you have any thoughts on what would be needed there?

I'm curious if there is anything I can do to help with HLS support. 🙂

**Comment by byte-sourcerer** [comment]
I have made a prototype for the extension of Haskell languager server. But currently it's blocked by this [bug](https://devforum.nova.app/t/lsp-doesnt-work-unless-re-activate-it/1798).

**Comment by willowell** [comment]
@cjwcommuny Do you have this prototype up on GitHub?

Also, since it's been 2 months since you last edited that post - have there been any changes since then?

**Comment by byte-sourcerer** [comment]
> Do you have this prototype up on GitHub?

Check the [download link](https://github.com/cjwcommuny/NovaHaskellLSP/releases/tag/prototype).

> have there been any changes since then?

It seems there are not…

**Comment by byte-sourcerer** [comment]
I have release a new [extension](https://extensions.panic.com/extensions/cjwcommuny/cjwcommuny.HaskellLSP/) to support it!
